### ISSUE TITLE
 Kaitai b32 result is inconsistent for some payload because of overflow 

### ISSUE THREAD

**Issue by spyapalli** [kaitai-io/kaitai_struct_csharp_runtime#12] opened 2019-01-30 20:29 UTC
The method ReadBitsIntLe() uses left shift operation which may contribute to overflow. We could use Math.Pow() method for left shift to avoid the overflow

                    ulong v = (ulong)(buf[i] * Math.Pow(2,BitsLeft));
                    //ulong v = (ulong)(buf[i] << BitsLeft);

I can make this change and send a pull request

**Comment by GreyCat** [comment] 2019-01-30 20:33
Could you specify an example of such payload, so we would add the test for that?

**Comment by spyapalli** [comment] 2019-01-30 20:44
Example: Payload in Hex 
d1 e7 ff ff 33 f5 ff ff 
The above payload has 8 * 8 = 64 bits. For the below kaitai it causes an overflow.

meta:
  id: qb975_v65538
  endian: le
seq:
  - id: first_val
    type: b32
  - id: second_val
    type: b32

The expected result should be 

first_val = 0x ff ff e7 d1
second_val = 0x ff ff f5 33

but currently we have a bug where the second_val will be wrong

Thanks
Sai

**Comment by GreyCat** [comment] 2019-01-30 20:57
I can't reproduce the problem. Expected results should be:

  [.] first_val = 3521642495 (0xd1e7ffff)
  [.] second_val = 871759871 (0x33f5ffff)

Actual results I'm getting in C# are:

3521642495
871759871

i.e. the same.

**Comment by spyapalli** [comment] 2019-01-30 21:03
Please use little Endian. The method is ReadBitsIntLe()

**Comment by GreyCat** [comment] 2019-01-30 21:07
There's no way to invoke that method from KSY now, so there are no real tests for it or anything like that. I suggest to start with building some tests for it first — it's kind of pointless to debug a method which you can't really even invoke with ksc.

**Comment by spyapalli** [comment] 2019-01-30 21:24
Because I am dealing with little Endian , I am invoking the method ReadBitsIntLe() in my code. And this method has a bug mentioned above. 

Also, do you have plans in future to support LE.

**Comment by GreyCat** [comment] 2019-01-31 13:28
Inviting @bibekdw (original contributor of this code) to discussion.

I suggest to move to https://github.com/kaitai-io/kaitai_struct/issues/155, discussing how we can implement this little-endian bit-level reading support in KSY.

**Comment by bibekdw** [comment] 2019-01-31 15:58
There is an overflow during left shift for this particular frame and following change is helping as mentioned by @spyapalli. I think there is no harm making this change.

`ulong v = (ulong)(buf[i] * Math.Pow(2,BitsLeft));`

**Comment by spyapalli** [comment] 2019-01-31 16:05
Hi 

Also, I realized there is a faster way to fix this. The Math.Pow function is little slower than the left shift. The better way is to cast it to ulong

ulong v = (ulong)((ulong)buf[i] << 24);

**Comment by bibekdw** [comment] 2019-01-31 16:21
@spyapalli sounds good.

**Comment by GreyCat** [comment] 2019-02-01 01:15
Looks like this particular bug is fixed now. I invite everyone to resume/join discusssion in https://github.com/kaitai-io/kaitai_struct/issues/155 for general question of implementing support for it in KS.

**Closed as completed by GreyCat** 2019-02-01 01:15 UTC
Labels: bug
